humanmade/hm-pattern-library

gulpfile.js, package.json, src/components/h1.html, src/components/h2.html, src/components/p.html, src/index.html
The `index.html` file in the root is compiled from the `src/index.html` file, which uses the `gulp`file`include` task.
Includes are formatted `@include( 'file.html' )  `.
All HTML components are in `src/components`. Current ones contain dummy content.
=> Add gulp-file-include for HTML partials

readme.md
Documents modifies Suit CSS naming convention in use for pattern library.
Fixes #19
=> Document CSS naming convention

gulpfile.js, package.json
We should include the SASS files in dist so that people can just grab dist and include it in their projects and still use the SASS.
=> Copy SASS to dist

src/js/NavAccordion.js, src/styles/base/_typography.scss, src/styles/components/_NavAccordion.scss, src/styles/vendor/_prismjs.scss
The toggle button was absolutely positioned, so links with long titles could overlap.
Better is to float right, so the text wraps around it. Only catch is the toggle needs to be prepended not appended - but I think thats fine.
Also snuck a couple of typography fixes in with this PR.
=> Fix nav accordion button overlap

src/html/components/search.html, src/html/index.html, src/js/SearchBar.js, src/styles/components/_SearchBar.scss
This JS relates ONLY to the style guide demo page, and should not be bundled with the released version. It should be up to whoever the implementation to handle this.
There's not much right now - so may aw well stick it in the footer. As/if it grows, we can maybe move into a separate file.
=> Split core JS and style guide JS

src/styles/base/_tables.scss
- If a th is at the bottom, we're not removing the bottom border.
- Table content is centered vertically by default. Looks pretty odd.
=> Fix bugs in tables.

src/styles/components/_Forms.scss, src/styles/components/_SearchBar.scss
Caused by opacity being set < 1 on the ::placeholder pseudo element, and any of the placeholder parent elements (including the actual input itself, right up to body) have position: relative or absolute applied.
Use RGBA colour instead.
See: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3901363/
Codepen: http://codepen.io/sambulance/pen/XNKQag
=> Fix form input placeholders not showing in MS Edge

assets/sass/_variables.scss, assets/sass/base/_typography-mixins.scss, assets/sass/base/_typography.scss, assets/sass/components/_wordpress-images.scss
I'm tweaking some typography and block spacing styles to match the designs in the new theme. Specifically, have been looking at styles from the default article page (https://zpl.io/Z1liyvC), which mainly includes different styles for headings, spacing around blockquotes, and spacing around image captions.
Here's a screenshot of the headings, note that I've bumped all styles up a level for semantic purposes.
Basing this of of the `v2-release` branch since that seems to be where things currently stand in https://github.com/humanmade/Human-Made-Website-Theme/
=> New theme style updates.

src/styles/base/_typography-mixins.scss, src/styles/components/_Buttons.scss
This contains three small changes needed while working on the homepage layout. Specifically:
* a `text-unlink` mixin for making links that inherit the color of their containers—useful for links inside headers in a post list.
* a new text size mixin between `text-md` and `text-lg` that I named `text-xm` (i.e., extra medium) for lack of a better name idea...suggestions welcome.
* Changes to the base button styles to match the button style for the new designs.
=> Redesign link and button tweaks

src/styles/base/_typography.scss
On focus the skip link did not show up.
Clip-path also needed to be disabled.
=> Also remove clip-path on focus

src/styles/base/_typography-mixins.scss, src/styles/components/_Buttons.scss
I was working on https://github.com/humanmade/Human-Made-Website-Theme/issues/154 and I think barbara has consolidated some of the font sizes across the site. I don't think we need both `md` and `xm` sizes, so I consolidated and tweaked the `md` and `lg` font size to match the site.  
Large text is used by section headings (important copy block) and the md text is used by things like case study titles on the what we do page and category nav in the blog.
=> Type tweaks - remove XM font size

src/styles/components/_hm-logo.scss
link on hm-logo
- add shover/focus style on link hm-logo
- removes double display: inline-block declaration on .hm-logo
Related to https://github.com/humanmade/Human-Made-Website-Theme/issues/295
=> Add missing focus and/or hover styles

gulp/gulp-svg.js, src/styles/_brand-colors.scss
[In this ticket](https://github.com/humanmade/Human-Made-Website-Theme/issues/325) we agreed upon #D14732 for the shade of red that meets accessibility requirements.
However it is listed as a slightly different shade here: https://drive.google.com/file/d/0B2okjXCGXwo2Nk1scUtzM2VZRlk/view
Visually - difference in the shade of red is almost impossible to see... but I'd like to be consistent! - @grarighe shall I updated the web pattern library to match?
=> Update hm-red to match guidelines

.circleci/config.yml, .circleci/deploy-exclude.txt, .circleci/deploy.sh, package.json
This will build the pattern library on circleci and do the following:
1. Push entire built project to `master-built` branch on merge to master
2. Push contents of `/dist/` to the `gh-pages` branch on merge to master
We could remove the `master-built` bit if you don't think it's needed but it could be handy for situations down the line, say if we add a react component library to this repo.
=> Automate building master and deploying gh-pages

src/html/components/cta.html, src/html/pages/components.html, src/styles/base/_typography-mixins.scss, src/styles/components/_cta.scss
Added a 24 pixel size link, for the CTAs with a grey background. Then they also comply with WCAG 2 AA (ratio 3.1 for larger text).
Discussed this with @grarighe 
This will be used on the HM site homepage with the "Join our team" link
=> Larger size cta link

src/styles/base/_images.scss, src/styles/base/_typography-mixins.scss, src/styles/base/_typography.scss
For a few reasons, it is not desirable to have headings on headings by default.
* Accessibility concerns.
* The H2 project - found them too heavy and not very readable.
* Blog posts about brands/technical writing - hard to capitalize correctly.
This keeps the caps around for the H1 tag though.
=> No uppercase titles h2-h6

src/html/pages/instructions.html
it originally said `$hm-images` which is never used in the pattern library.
=> update the variable name for images path

src/html/components/code-block.html, src/html/components/hr.html, src/html/components/lists.html, src/html/pages/base.html, src/styles/base/_typography-mixins.scss, src/styles/base/_typography.scss, src/styles/style-guide.scss
I'm looking at fixing a few style issues in the Engineering Handbook, where Ryan has overridden some of the pattern library styles. I think he was trying to tighten the text styles up a bit, reducing some excess margins etc. to improve legibility.
* Reduce margins between paragraphs. 
* Reduce bottom margin on headings. 
* Improve list styles
* Add hr styles
* Reduce blockquote margins.
* Improve code text styles. Apply font-family and other styles to non prism code blocks.
=> Update typography styles. 

package-lock.json, package.json, readme.md
Updating repo for v2.1.0 release:
The Git tag `2.1.0` has already been created, this PR bumps the versions to this tag and adds updates the changelog with the details https://github.com/humanmade/hm-pattern-library/releases/tag/2.1.0
- Updated Changelog
- Version bump to `2.1.0` for `package.json`
- Updated `package-lock.json` via `npm install` for `2.1.0` version bump
=> v2.1.0 Release

src/styles/base/_typography-mixins.scss
Using borders for underlining is already bad, but using a variable-width border causes all kinds of layout pain. Hovering a link should not cause the entire subsequent page to reflow.
Also restores outline on focused link for accessibility
=> Adjust link border defaults to prevent page reflow
