humanmade/hm-pattern-library

- package.json
> Add gulp-sass to package.

- gulpfile.js
> Build to dist directory.

- index.html
- src/styles/_variables.scss
- src/styles/base/_border-box.scss
- src/styles/components/_Swatch.scss
- src/styles/style.scss
- src/styles/utilities/_clearfix.scss
Brand swatches
Also includes changing the box model to border-box for ease of use.
See #6
> 6 brand swatches

- .sass-lint.yml
- src/styles/_variables.scss
- src/styles/components/_Swatch.scss
Few places this wasn't done. I think we should enforce it one way or another.
> Enforce no space before colon

- readme.md
> First pass, pattern library readme.

- gulpfile.js
- src/html/index.html
- src/styles/_variables.scss
- src/styles/components/_Logo.scss
- src/styles/style-guide.scss
Not yet merge ready.
Fixes #25
> Include assets folder in dist directory.

- src/styles/_variables.scss
- src/styles/base/_tables.scss
- src/styles/base/_typography.scss
- src/styles/components/_Logo.scss
- src/styles/components/_wordpress-images.scss
Should use variables for these measurements for consistency. Added a gutter width var too as we have a bunch of horizontal things to keep consistent.
Fixed image paths - github pages is stricter than my local on the caps.
> Wp image fixes

- src/html/components/colour-swatches.html
- src/styles/_variables.scss
- src/styles/base/_typography.scss
- src/styles/components/_Swatch.scss
- src/styles/components/_wordpress-images.scss
- src/styles/style-guide.scss
Replaces Light Beige with Beige. 
Fixes #38
> Correct beige variable name

- src/html/index.html
- src/js/NavAccordion.js
Updated to use vanilla JS only.
> Nav accordion no jquery

- src/styles/base/_typography.scss
- src/styles/components/_Buttons.scss
- src/styles/components/_Logo.scss
- src/styles/components/_NavAccordion.scss
- src/styles/components/_SearchBar.scss
- src/styles/style.scss
- src/styles/vendor/_prismjs.scss
Ran into a few smaller things to fix whilst implementing this in the handbook. Mostly minor tweaks to typography & colours.
> Misc fixes

- src/js/NavAccordion.js
- src/styles/components/_NavAccordion.scss
Small refactor of the accordion JS to collapse navigation more than 1 level deep
> Collapse nested nav menus

- src/html/components/buttons.html
- src/styles/components/_Buttons.scss
> Disabled button styles

- src/html/components/nav-accordion.html
- src/js/NavAccordion.js
- src/styles/components/_NavAccordion.scss
If an item is the current page, and it has a sub menu, then that sub menu should be expanded on page load
> Nav - expand child if top level is current

- src/styles/components/_NavAccordion.scss
https://github.com/humanmade/hm-pattern-library/issues/62
> Reduce line height for nav

- src/html/components/search.html
- src/styles/components/_SearchBar.scss
Hover style for search results.
Also drop down to have very subtle opacity to give a little better context
Finally overflow auto on the search results container to allow for scrolling.
> Hover style for search bar

- src/styles/_defaults.scss
- src/styles/_variables.scss
- src/styles/base/_tables.scss
- src/styles/base/_typography.scss
- src/styles/components/_Buttons.scss
- src/styles/components/_Footer.scss
- src/styles/components/_Forms.scss
- src/styles/components/_Loading.scss
- src/styles/components/_Logo.scss
- src/styles/components/_NavAccordion.scss
- src/styles/components/_SearchBar.scss
- src/styles/components/_Swatch.scss
- src/styles/components/_wordpress-galleries.scss
- src/styles/components/_wordpress-images.scss
- src/styles/style.scss
- src/styles/themes/_backgrounds.scss
when used in  hm-handbook and also in child themes of hm handbok
> mapping variables to make it easier to over ride

- src/styles/_variables.scss
to not always be hm-red but the set default color-primary
> fixing the lightening and darkening of colour-rpimary 

- src/styles/base/_typography-mixins.scss
- src/styles/base/_typography.scss
- src/styles/components/_Buttons.scss
- src/styles/style.scss
Makes it easier to reuse.
See https://github.com/humanmade/hm-pattern-library/issues/89
> Separate type + type mixins. Add link mixin

- src/html/components/blockquote.html
- src/html/components/table.html
- src/styles/base/_typography.scss
Accessibility tweaks, see #91 
Todo: the Accordion, is not keyboard accessible enough at the moment.
The colour issues are for the designers
> Accessibility

- src/html/components/nav-accordion.html
- src/js/NavAccordion.js
- src/styles/base/_typography-mixins.scss
- src/styles/components/_NavAccordion.scss
A11y improvement of the NavAccordion
> Accessibility NavAccordion

- src/styles/_variables.scss
- src/styles/base/_typography-mixins.scss
- src/styles/base/_typography.scss
- src/styles/components/_wordpress-images.scss
Hey @joemcgill Does this look like it covers your changes?
> Backport joes updates

- src/styles/base/_typography-mixins.scss
- src/styles/components/_NavAccordion.scss
This addresses https://github.com/humanmade/Human-Made-Website-Theme/issues/59
> Remove focus outline style on links

- src/html/components/small-text.html
- src/html/pages/base.html
- src/styles/base/_typography-mixins.scss
- src/styles/base/_typography.scss
Fixes https://github.com/humanmade/Human-Made-Website-Theme/issues/162
> Fix line height of small text

- src/styles/base/_typography-mixins.scss
- src/styles/utilities/_icons.scss
See https://github.com/humanmade/Human-Made-Website-Theme/pull/217
> Update link styles

- src/styles/base/_typography-mixins.scss
See https://github.com/humanmade/Human-Made-Website-Theme/issues/148
> Remove visited link color

- gulp/gulp-svg.js
- src/styles/_brand-colors.scss
- src/styles/_variables.scss
Single shade of red for all that meets accessibility requirements.
> Consolidate brand red

- src/styles/base/_typography-mixins.scss
See #441 Human-Made-Website-Theme
https://github.com/humanmade/Human-Made-Website-Theme/issues/441
Makes the underline border a more visible colour
> 441 HMWT Change colour underline border

- gulp/gulp-lint.js
- gulp/gulp-styles.js
- gulp/gulp-svg.js
- gulpfile.js
- package-lock.json
- package.json
- Ran `npm audit --fix --force`
- Compatibility with gulp 4
> Update npm dependencies to fix vulnerabiliteies

- .travis.yml
- gulp/gulp-html.js
- gulp/gulp-images.js
- gulp/gulp-js.js
- gulp/gulp-lint.js
- gulp/gulp-styles.js
- gulp/gulp-svg.js
- gulp/index.js
- gulpfile.js
- package-lock.json
- package.json
- src/styles/base/_functions.scss
- src/styles/base/_tables.scss
- src/styles/base/_typography.scss
- src/styles/components/_buttons.scss
- src/styles/components/_cta.scss
- src/styles/components/_forms.scss
- src/styles/components/_hm-logo.scss
- src/styles/components/_labels.scss
- src/styles/components/_pagination.scss
- src/styles/components/_swatch.scss
- src/styles/components/_tag-cloud.scss
- src/styles/components/_wordpress-galleries.scss
- src/styles/components/_wordpress-images.scss
- src/styles/style-guide.scss
- src/styles/vendor/_prismjs.scss
Fix the build on newer machines and new versions of node. This now works fine on my M1 mac running Node 16.
> Get build working on node 16 and for M1 macs
